apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:UCjs/ormqEgBfgy57db3CMkQRHYmFkrxXwFvEFPfaH+7Xz/pXMQ2mn9XPlG+ie3AFMYyuZ/3/S5+bnC/9O4ynrJ7UGJ7CW1+WTSPCdXC8zv9TIAQuEWOsYrOoAYpnwAjAhxhEbLkOoRIvN8sojfCB3BaHEfjrXKpJz0FuNekb2rfTSccBur8ucu7Nsu804fhRUHtlfUcE5sx6D+1dRWok+KBVL/HkwcT5Ekvrm3qIEeDA8fQyzG/sOeOnNb2Af+7bdxwO0A5CciUKdX7Wva2ZQDM4gTSl5u/Ymnj5apzv/8H6LOWMnv/wW8w2yI=,iv:D/64JspSgTYK+vNgN6OK7HhOc3f4iGj9lOUdumUNhW8=,tag:qbj/DO3OpHRGdb4UDK+kOA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1sghkzrk44vnyq2l6uxex9ss9vzvpcm48jzgt26nvcn2maqwd04fscwx3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNmMxWCtwRng0d3J0emgw
            ZUpyTHhCckJ2T3IwZUV5MzJlZ3dkRkRhR1FBCjY3ZGZuR0Y2NGlNZkhWYmw2VjJT
            M3BKdEF3ZndaZHZ6N1NFTDZMSDdxa2MKLS0tIDNBV083QWdlM1VmQTdDYnpPeStw
            dDA4N05JQ21ZVnFScHU1MkVzalBYbXcKADjBA0eoMZDTTra3mxLxn1YuBiSuqurU
            4llFhSW/qwHIFTLGZg830GbyffSdEtXu5WctTN4SMzoZ1L+i+LwYug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T18:00:17Z"
    mac: ENC[AES256_GCM,data:6XuhVxBaxepTVUpaq3sBIqil77FdcL4lxUER/WvZtZm0+7fiydYgT0si86gsf0Haopm9J9FssBy8KxqkPZtIj1661pic1OryN/xwzxmM8jqWtD44i0SSL5Cff1Py1TJHXl8D5CWXqwlCvhbpnhtwfpJYZadpwD0EWD3EXzlDoY0=,iv:6KKEHhXxCi/1KDGD4jOANLU6+HCklfVdGq26fkHFa5M=,tag:7eJMGmZWf7t1TM1T9PBZiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
