apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Ia7yoOi+VvAiPqj8DCzBTvVGKJQeAEa8OjvZJBz9u8dBjys6niEN+1rfHIrnjkT/yvhNyiFtoh+hI38Ujllr6pRMl1yDq4ovF+KlNX9jRFrBryCsGJuwOO/KcFuUrzm000BwNclMpbABBdfKqkZOMArIyOOzB5yk6QmpQ7eci5PHWwq0oQVmOZbCoSRtZ5czYiBUuqqb/CCV2iVXmYSXgnC88tl7r/IJHBTxfi0pWLYBbLtI6dwTa8emgKiE0M/T+JFQgmkNoZ9P9xwGrk8VScNTf+kFXLes2zF668pjWAltc0t4lMMVEaPrbbU=,iv:aKR+1klEKdPgKpOOfqQoIHrMuSFHwub5pyU43TdX/a8=,tag:sLGretOU44IDklV7Vzabgg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1sghkzrk44vnyq2l6uxex9ss9vzvpcm48jzgt26nvcn2maqwd04fscwx3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUWFlS3dVL1FFNDNEdjdm
            cTFQcjdTblhMQzl2Q2xxcmNmeDZnNkRJVGw0CmdIZk15TmxQT0tsZzBMZ083aldY
            YUVoYWI0a1Vva29qdE1kMjVIQldYUVEKLS0tIDhFa1RRbjVpcnA0YUtLdmJma3Rz
            ZGxPaHVrU3dMWFFuV01EelRTT1ZzMlEKv5/ytrxH5g7ypfngn76qKDDjBAQnJq7A
            4mPKtajpmLe7U+Rs1EwTyuMPhgg84DLMtgzCO8WzaaaquOY+QNr33g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T19:46:25Z"
    mac: ENC[AES256_GCM,data:ZPl6nFOR7M1XifTWaqTx+uhEj0BcmKEK9pWGW6doqgd2hmMQiBtGv2nrhs0PYLzkZZcDvvdnq6SQlalG+vPpTjV3ilKqcESHm4+9y56JfUGuK7ZKQ05+WNputivm+o4jzNHZan9Qweh50g41OvKX+SZPnqylmNawvHMvcDwItGE=,iv:ggLdnDtl0aBACq1CSg5p91Rm7NB2NO1OYc2f9TR1cy0=,tag:bTnmJrWv+LSjanicsJJXqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
