apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '77.9.1'
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: paddy
      ingress:
        enabled: true
        ingressClassName: traefik

        labels: {}

        hosts:
          - grs.wolkenwerk.org

        ## TLS configuration for grafana Ingress
        ## Secret must be manually created in the namespace
        ##
        tls: 
         - secretName: grafana-tls-secret
           hosts:
           - grs.wolkenwerk.org
